### ISSUE TITLE
Publication of Models

### ISSUE THREAD

**Issue by lamsoma** [FloatFrank/TIPA#1]
I would like to actually use TIPA and MTIPA, but would you be willing to release the code for training and models on huggingface? Also, I would appreciate it if you could release the code to generate MTIPA.

**Comment by FloatFrank** [comment]
> I would like to actually use TIPA and MTIPA, but would you be willing to release the code for training and models on huggingface? Also, I would appreciate it if you could release the code to generate MTIPA.

Of course, thank you for your attention. I will open source the MTIPA code, corresponding training code, and related models within the next two days

**Comment by FloatFrank** [comment]
All code and datasets have been uploaded, and the models have been uploaded to Huggingface for your review. However, it should be noted that these models are trained specifically for Chinese. If you intend to use them for languages such as Japanese or Korean, you may need to retrain them.

[**MTIPA-E1**](https://huggingface.co/LLMMINE/MTIPA-7B-PositionTask) | [**TIPA-E2**](https://huggingface.co/LLMMINE/TIPA-7B-TranditionalTask)

**Comment by lamsoma** [comment]
感谢您发布该模型。我有一个关于 "huggingface "模型的问题：当我使用 LLMMINE/MTIPA-7B-PositionTask 时，我得到以下警告：找不到与 LoRA 相关的权重，它似乎无法正常工作。TIPA 工作正常。
`UserWarning: Found missing adapter keys while loading the checkpoint: ['base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight', 'base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight’,・・・・`
